// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9TQAbSY8qQz2m7vWuQ495p7lcK3-KFdw',
    appId: '1:1006684929020:web:98df6e310f99cf49375079',
    messagingSenderId: '1006684929020',
    projectId: 'ommobor-hisobot',
    authDomain: 'ommobor-hisobot.firebaseapp.com',
    storageBucket: 'ommobor-hisobot.firebasestorage.app',
    measurementId: 'G-RCN1LQNDGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvtPzn3y_iXejRHT1Cd_lTSTPamZx6xy8',
    appId: '1:1006684929020:android:3f43e5edca21736a375079',
    messagingSenderId: '1006684929020',
    projectId: 'ommobor-hisobot',
    storageBucket: 'ommobor-hisobot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA58f6rzXWlxaGt24ev_-glkJD5-tHjdjA',
    appId: '1:1006684929020:ios:82eac8e54530250b375079',
    messagingSenderId: '1006684929020',
    projectId: 'ommobor-hisobot',
    storageBucket: 'ommobor-hisobot.firebasestorage.app',
    iosBundleId: 'com.example.omborHisobot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA58f6rzXWlxaGt24ev_-glkJD5-tHjdjA',
    appId: '1:1006684929020:ios:82eac8e54530250b375079',
    messagingSenderId: '1006684929020',
    projectId: 'ommobor-hisobot',
    storageBucket: 'ommobor-hisobot.firebasestorage.app',
    iosBundleId: 'com.example.omborHisobot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9TQAbSY8qQz2m7vWuQ495p7lcK3-KFdw',
    appId: '1:1006684929020:web:5ba15a623e07b792375079',
    messagingSenderId: '1006684929020',
    projectId: 'ommobor-hisobot',
    authDomain: 'ommobor-hisobot.firebaseapp.com',
    storageBucket: 'ommobor-hisobot.firebasestorage.app',
    measurementId: 'G-7YPWRXW6BV',
  );
}
